# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-octavo-osd32mp1"
BBFILE_PATTERN_meta-octavo-osd32mp1 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-octavo-osd32mp1 = "6"

# for optee-os-stm32mp dependency
LAYERDEPENDS_meta-octavo-osd32mp1 = "core openembedded-layer meta-python"
LAYERSERIES_COMPAT_meta-octavo-osd32mp1 = "mickledore"
LAYERVERSION_meta-octavo-osd32mp1 = "1"

EULA_FILE_ST:stm32mpcommon = "${LAYERDIR}/conf/eula/${MACHINE}"
EULA_FILE_ST_MD5SUM:stm32mpcommon = "1c485682b3ceeae0c296ba593235bd69"

# OpenSTLinux compatibility version
ST_OSTL_COMPATIBILITY_VERSION_meta-octavo-osd32mp1 = "5.1"
